### ISSUE TITLE
Planetwars Todo

### ISSUE THREAD

**Issue by GoogleFrog** [ZeroK-RTS/Chobby#175]
- [x]  Add the timer which says how long the phase has to go.
 - [x] Add instructions at the top of the PW MP tab. If you lack engine or game tell the player. Give instructions "Enemy faction is currently selecting a planet to attack.", "Invasion launched, wait for enemy faction to muster a defense", "Your turn to attack, select a planet to invade", "Enemy invasion launched, join the defense".
 - [x] Add top status box which tells you to join an attack that needs 1 player or to join defense.
 - [x] Implement PwRequestJoinPlanet for site-induced joins

Single vote or multi-vote need updates.
 - [x] With single vote the buttons need to be un-clicked upon clicking a different button.
 - [ ] With multi-vote there should really be a way of un-clicking buttons.

**Comment by Licho1** [comment]
Also the download map button on planet should auto attack when done.
Otherwise it is very annoying because you have to either wait on that screen for download to finish or remember to return there and click attack.
It should be single click action.

**Comment by GoogleFrog** [comment]
Done. I am unable to test much though.

**Comment by Licho1** [comment]
Issues detected:
 * when there is 1v1 mm and you are waiting for other faction defense, it shows "join planet" popup as well, clicking it lures you into MM instead :)
 * after you join and "attack" planet there is no feedback, top bar disappears and you dont know if it worked or not, it should stay there if you are the one to play

**Comment by Sortale** [comment]
planet map too small can not make out map terrain

**Comment by GoogleFrog** [comment]
Done.
